# Prueba de compilación
name: Compilation Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verificar sintaxis del proyecto
        run: |
          python -m py_compile app.py
          python -m py_compile database.py
          python -m py_compile detector.py
          python -m py_compile insertar.py
          python -m py_compile alerts.py
